language: cpp

matrix:
  include:
    - os: windows
      env:
        - PATH=/c/Qt/5.14.2/mingw73_64/bin:/c/Qt/Tools/mingw730_64/bin:/c/ProgramData/chocolatey/bin/:/c/sqlite/:$PATH
        - BUILD_DIR=build
        - BOOST_ROOT=/c/Boost
        - BOOST_INCLUDEDIR=/c/Boost/include/boost_1_73_0/
      before_install:
        - wget -q https://download.qt.io/official_releases/qt/5.14/5.14.2/qt-opensource-windows-x86-5.14.2.exe
        - dir /C/ProgramData/chocolatey/bin/
        - pip.exe install --upgrade pip
        - pip.exe install requests
      install:
        - ./qt-opensource-windows-x86-5.14.2.exe --script ./scripts/qt_windows_installer.qs
        - python.exe ./scripts/install_env.py
        - choco install sqlite
        - choco install doxygen.install
        - choco install graphiz
      cache:
        directories:
          - boost_1_73_0/
      script:
        - mkdir ${BUILD_DIR} && cd ${BUILD_DIR}
        - cmake .. -G "MinGW Makefiles"
        - mingw32-make

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - graphviz
            - doxygen
            - sqlite3 libsqlite3-dev
            - qt5-default
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
        - BUILD_DIR=build
        - PROJECT_NAME=AppChat
      before_install:
        - eval "${MATRIX_EVAL}"
      before_script:
        - sudo python3 ./scripts/install_env.py
      script:
        - mkdir ${BUILD_DIR}
        - cd ${BUILD_DIR}
        - cmake ..
        - cmake --build .
      after_success:
        - cd ${TRAVIS_BUILD_DIR}/${BUILD_DIR}/bin/release
        - tar -cf  AppChat-0.7.$TRAVIS_BUILD_NUMBER-Linux.tar appchat-server appchat-client
        - >-
            if [[ "$TRAVIS_BRANCH" = "master" && -n "$TRAVIS_BUILD_DOCS" ]] ; then
              cd $TRAVIS_BUILD_DIR
              echo 'Generating Doxygen code documentation...'
              # Redirect both stderr and stdout to the log file AND the console.
              doxygen doc/Doxyfile 2>&1 | tee doxygen.log
            fi
            if [[ "$TRAVIS_BRANCH" = "master" ]] ; then
              curl -T ${TRAVIS_BUILD_DIR}/${BUILD_DIR}/release/appchat-server-0.7.$TRAVIS_BUILD_NUMBER-Linux.deb -uk-morozov:$BINTRAY_API_KEY "https://api.bintray.com/content/k-morozov/AppChat/server/server-linux/appchat-server-0.7.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=bionic;deb_component=main;deb_architecture=amd64;publish=1"
              curl -T ${TRAVIS_BUILD_DIR}/${BUILD_DIR}/release/appchat-client-0.7.$TRAVIS_BUILD_NUMBER-Linux.deb -uk-morozov:$BINTRAY_API_KEY "https://api.bintray.com/content/k-morozov/AppChat/client/client-linux/appchat-client-0.7.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=bionic;deb_component=main;deb_architecture=amd64;publish=1"
            fi
      before_deploy:
        - git config --local user.name "k-morozov"
        - git config --local user.email "morozov-kst@yandex.ru"
        - git tag 0.7.$TRAVIS_BUILD_NUMBER-Linux
      deploy:
        - provider: releases
          api_key: $GITHUB_API_KEY
          file: AppChat-0.7.$TRAVIS_BUILD_NUMBER-Linux.tar
          skip_cleanup: true
          on:
            branch: release
        - provider: pages
          skip_cleanup: true
          token: $GITHUB_API_KEY
          keep_history: true
          local_dir: docs/html
