language: cpp
os:
  - windows

before_install:
  - choco install python3 --params "/InstallDir:C:\Python"
  - C:/Python/python3.exe /scripts/install_env.py

install:
  - ./qt-opensource-windows-x86-5.14.2.exe --script ./scripts/qt_windows_installer.qs
  
script:
  - mkdir ${BUILD_DIR}
  - cd ${BUILD_DIR}
  - cmake ..
  - cmake --build .
