language: cpp
os:
  - windows

before_install:
  - python3 /scripts/install_env.py
  - wget -q https://download.qt.io/official_releases/qt/5.14/5.14.2/qt-opensource-windows-x86-5.14.2.exe

install:
  - ./qt-opensource-windows-x86-5.14.2.exe --script ./scripts/qt_windows_installer.qs
  
script:
  - mkdir ${BUILD_DIR}
  - cd ${BUILD_DIR}
  - cmake ..
  - cmake --build .
