dist: bionic
language: cpp
compiler: gcc

before_script:
  - sudo apt-get update
  - sudo apt-get install sqlite3 libsqlite3-dev
  - sudo apt-get install doxygen
#boost 1.73.0
  - wget -O boost_1_73_0.tar.gz https://sourceforge.net/projects/boost/files/boost/1.73.0/boost_1_73_0.tar.gz/download
  - tar -xf boost_1_73_0.tar.gz 
  - cd boost_1_73_0
  - sudo ./bootstrap.sh --prefix=/usr/local
  - sudo ./b2 link=static runtime-link=shared install
# end boost
#gtest
  - sudo apt-get install libgtest-dev -y 
  - sudo chmod 777 /usr/src/gtest
  - cd /usr/src/gtest 
  - cmake .
  - make
  - sudo cp *.a /usr/lib/
  - cd "${TRAVIS_BUILD_DIR}"
# end gtest
  - sudo apt install qt5-default
script:
  - mkdir build
  - cd build
  - cmake ..
  - make

#  - cd ${TRAVIS_BUILD_DIR}/bin/
#  - pwd
#  - ls
#  - cmake --build . --target test
#  - cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
  # ${TRAVIS_BUILD_DIR}/bin/server-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb
  # "https://api.bintray.com/content/k-morozov/AppChat/Chat/$TRAVIS_BUILD_NUMBER/server-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=bionic;deb_component=main;deb_architecture=amd64;publish=1"
  #${PROJECT_NAME}-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb
  - curl -T ${TRAVIS_BUILD_DIR}/bin/server -uk-morozov:$BINTRAY_API_KEY "https://api.bintray.com/content/k-morozov/AppChat/Chat/$TRAVIS_BUILD_NUMBER/server-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=bionic;deb_component=main;deb_architecture=amd64;publish=1"
  - curl -T ${TRAVIS_BUILD_DIR}/bin/client -uk-morozov:$BINTRAY_API_KEY "https://api.bintray.com/content/k-morozov/AppChat/Chat/$TRAVIS_BUILD_NUMBER/client-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=bionic;deb_component=main;deb_architecture=amd64;publish=1"
