#dist: bionic
language: cpp
compiler: gcc
sudo: required
os:
  #  - linux
  - windows

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
    - dist: bionic
        before_script:
          - sudo python3 /scripts/install_env.py
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - graphviz
            - doxygen
            - sqlite3 libsqlite3-dev
            - libboost-test-dev
            - qt5-default
          cache:
            directories:
              - $HOME/boost_1_67_0/boost
              - $HOME/boost_1_67_0/stage/lib
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
        - BUILD_DIR=build
        - PROJECT_NAME=AppChat
    - os: windows
        before_install:
          - python3 /scripts/install_env.py
          - wget -q https://download.qt.io/official_releases/qt/5.14/5.14.2/qt-opensource-windows-x86-5.14.2.exe
        install:
          - ./qt-opensource-windows-x86-5.14.2.exe --script ./scripts/qt_windows_installer.qs
  
before_install:
    - eval "${MATRIX_EVAL}"

script:
  - mkdir ${BUILD_DIR}
  - cd ${BUILD_DIR}
  - cmake ..
  - cmake --build .
  - 
    #  - cmake --build . --target test
    #  - cmake --build . --target package

after_success:
  #- cd ${TRAVIS_BUILD_DIR}/${BUILD_DIR}/bin
  #- tar -cf  AppChat-0.7.$TRAVIS_BUILD_NUMBER-Linux.tar server client
  #- >-
  #    if [[ "$TRAVIS_BRANCH" = "master" && -n "$TRAVIS_BUILD_DOCS" ]] ; then
  #      cd $TRAVIS_BUILD_DIR
  #      echo 'Generating Doxygen code documentation...'
  #      # Redirect both stderr and stdout to the log file AND the console.
  #      doxygen doc/Doxyfile 2>&1 | tee doxygen.log
  #    fi
  #
  #    if [[ "$TRAVIS_BRANCH" = "master" ]] ; then
  #        curl -T ${TRAVIS_BUILD_DIR}/build/bin/AppChat-0.7.$TRAVIS_BUILD_NUMBER-Linux.tar -uk-morozov:$BINTRAY_API_KEY https://api.bintray.com/content/k-morozov/AppChat/Download/0.7.$TRAVIS_BUILD_NUMBER/AppChat-0.7.$TRAVIS_BUILD_NUMBER-Linux.tar
  #        curl -T ${TRAVIS_BUILD_DIR}/${BUILD_DIR}/${PROJECT_NAME}-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uk-morozov:$BINTRAY_API_KEY "https://api.bintray.com/content/k-morozov/AppChat/Install-Linux/0.7.$TRAVIS_BUILD_NUMBER/${PROJECT_NAME}-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=bionic;deb_component=main;deb_architecture=amd64;publish=1"
  #    fi

  #before_deploy:
  #    - git config --local user.name "k-morozov"
  #    - git config --local user.email "morozov-kst@yandex.ru"
  #    - git tag 0.7.$TRAVIS_BUILD_NUMBER-Linux
  #deploy:
  #    - provider: releases
  #      api_key: $GITHUB_API_KEY
  #      file: AppChat-0.7.$TRAVIS_BUILD_NUMBER-Linux.tar
  #      skip_cleanup: true
  #      on:
  #        branch: release
  #
  #deploy:
  #    - provider: pages
  #      skip-cleanup: true
  #      github-token: $GITHUB_API_KEY
  #      keep-history: true
  #      local-dir: docs/html

