dist: bionic
language: cpp
sudo: required
compiler:
    - gcc
os:
  - linux

before_script:
    - ls
    - if [ $TRAVIS_OS_NAME == linux ]; then sudo ./scripts/install_env.sh; fi
script:
    - cmake --version
    - cmake CMakeLists.txt
    - cmake  --build . --target
  #- mkdir build
  #- cd build
  #- cmake ..
  # - make
  # - cmake --build ..
  #- cmake --build .. --server package
  #- cd src/server
  #- ls
  #- make package
  # - cd ${TRAVIS_BUILD_DIR}/bin
  # - ls
#  - jar cfe artefact.jar server client
#  - cmake --build . --target test
#  - cmake --build . --target package
after_success:
  # Generate the docs only if master, and the TRAVIS_BUILD_DOCS is not zero
  - >-
    if [[ "$TRAVIS_BRANCH" = "master" && -n "$TRAVIS_BUILD_DOCS" ]] ; then
      cd $TRAVIS_BUILD_DIR
      echo 'Generating Doxygen code documentation...'
      # Redirect both stderr and stdout to the log file AND the console.
      doxygen doc/Doxyfile 2>&1 | tee doxygen.log
    fi
deploy:
    provider: script
    skip_cleanup: true
    script:
      - curl -T ${TRAVIS_BUILD_DIR}/bin/server -uk-morozov:$BINTRAY_API_KEY https://api.bintray.com/content/k-morozov/AppChat/Server/$TRAVIS_BUILD_NUMBER/server && curl -T ${TRAVIS_BUILD_DIR}/bin/client -uk-morozov:$BINTRAY_API_KEY https://api.bintray.com/content/k-morozov/AppChat/Client/$TRAVIS_BUILD_NUMBER/client
    
    #provider: pages
    #skip-cleanup: true
    #github-token: $GITHUB_API_KEY
    #keep-history: true
    #local-dir: docs/html
    #on:
        #branch: master
