language: cpp
env:
  - BUILD_DIR=build
os:
  - windows

before_install:
  - wget -q https://download.qt.io/official_releases/qt/5.14/5.14.2/qt-opensource-windows-x86-5.14.2.exe

install:
  - ./qt-opensource-windows-x86-5.14.2.exe --script ./scripts/qt_windows_installer.qs
  - choco install python3 --params "/InstallDir:C:\Python"
  - C:/Python/python.exe -m pip install requests
  - C:/Python/python.exe ./scripts/install_env.py
  - setx /m PATH %PATH%;C:\Qt\5.14.2\mingw73_64\bin
  
script:
  - mkdir ${BUILD_DIR}
  - cd ${BUILD_DIR}
  - cmake ..
  - cmake --build .
