language: cpp

matrix:
  include:
    - os: windows
        env:
          - PATH=/c/Qt/5.14.2/mingw73_64/bin:/c/Qt/Tools/mingw730_64/bin:/c/Python:/c/Python/Scripts:/c/sqlite/:$PATH
          - BUILD_DIR=build
          - BOOST_ROOT=/c/Boost
          - BOOST_INCLUDEDIR=/c/Boost/include/boost_1_73_0/
        before_install:
          - wget -q https://download.qt.io/official_releases/qt/5.14/5.14.2/qt-opensource-windows-x86-5.14.2.exe
          - choco intall python3 --params "/InstallDir:C\Python"
          - python.exe -m pip install --upgrade pip
          - python.exe -m pip install requests
        install:
          - ./qt-opensource-windows-x86-5.14.2.exe --script ./scripts/qt_windows_installer.qs
          - python.exe ./scripts/install_env.py
          - choco install sqlite
          - choco install doxygen.install
          - choco install graphiz
        cache:
          directories:
            - boost_1_73_0/
        script:
          - mkdir ${BUILD_DIR} && cd ${BUILD_DIR}
          - cmake .. -G "MinGW Makefiles"
          - mingw32-make
