language: cpp
compiler:
  - clang
before_script:
  - sudo apt-get update
  - sudo apt-get install sqlite3 libsqlite3-dev
  - sudo apt-get install sqlite
  - sudo apt-get install libboost-all-dev
  - sudo apt-get install libgtest-dev
  - sudo apt install qt5-default
#gtest
  - sudo apt-get install libgtest-dev -y 
  - sudo chmod 777 /usr/src/gtest
  - cd /usr/src/gtest 
  - cmake .
  - make
  - sudo cp *.a /usr/lib/
# end gtest
  - cd "${TRAVIS_BUILD_DIR}"
script:
  - cmake -DLLVM_ENABLE_PROJECTS=clang .
  - cmake --build .
