language: cpp
os:
  - windows

before_install:
  - choco install python3 --params "/InstallDir:C:\Python"
  - cd C:\Python
  - dir

install:
  - ./qt-opensource-windows-x86-5.14.2.exe --script ./scripts/qt_windows_installer.qs
  
script:
  - mkdir ${BUILD_DIR}
  - cd ${BUILD_DIR}
  - cmake ..
  - cmake --build .
